org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
android.suppressUnsupportedCompileSdk=36
